config/routes.rb
Rails.application.routes.draw do
  root to: 'messages#index'
  resources :contacts
  resources :messages, except: [:destroy, :update, :edit]
end

#       Prefix Verb   URI Pattern                  Controller#Action
#     contacts GET    /contacts(.:format)          contacts#index
#              POST   /contacts(.:format)          contacts#create
#  new_contact GET    /contacts/new(.:format)      contacts#new
# edit_contact GET    /contacts/:id/edit(.:format) contacts#edit
#      contact GET    /contacts/:id(.:format)      contacts#show
#              PATCH  /contacts/:id(.:format)      contacts#update
#              PUT    /contacts/:id(.:format)      contacts#update
#              DELETE /contacts/:id(.:format)      contacts#destroy
#     messages GET    /messages(.:format)          messages#index
#              POST   /messages(.:format)          messages#create
#  new_message GET    /messages/new(.:format)      messages#new
#      message GET    /messages/:id(.:format)      messages#show

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  before_create :send_message

private

  def send_message
    begin
      response = RestClient::Request.new(
        :method => :post,
        :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => { :Body => body,
                      :MediaURL => media_url,
                      :To => to,
                      :From => from }
      ).execute
    rescue RestClient::BadRequest => error
      message = JSON.parse(error.response)['message']
      errors.add(:base, message)
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:notice] = "Your contact was saved!"
      redirect_to contacts_path
    else
      render 'new'
    end
  end

  def show
    @contact = Contact.find(params[:id])
  end

private
  def contact_params
    params.require(:contact).permit(:name, :phone)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
    respond_to do |format|
       format.js
     end
  end

  def create
    @phones = message_params[:to].slice(0..-2)
    @phones.each do |phone|
      @message = Message.new(to: phone, from: message_params[:from], body: message_params[:body], media_url: message_params[:media_url])
      if @message.save
        flash[:notice] = "Your message was sent!"
        respond_to do |format|
          format.js
        end
      else
        render 'new'
      end
    end
  end

  def show
    @message = Message.find(params[:id])
  end

private
  def message_params
    params.require(:message).permit({to: []}, :from, :body, :media_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_contact.html.erb
<p><%= link_to contact.name, contact_path(contact) %></p>

app/views/contacts/index.html.erb
<h2>Contacts</h2>

<%= render @contacts %>

<p><%= link_to 'New Contact', new_contact_path %></p>

app/views/contacts/new.html.erb
<h2>New Contact</h2>

<% if @contact.errors.any? %>
  <p> say what? </p>
  <ul>
    <% @contact.error.full_messages.each do |message| %>
        <li> <%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @contact do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Texter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash[:notice] %>
<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<% if @message.errors.any? %>
  <p> say what? </p>
  <ul>
    <% @message.error.full_messages.each do |message| %>
        <li> <%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @message, :html => { :multipart => true }, remote: true do |f| %>
  <%= f.label :to %>
  <%= f.collection_check_boxes(:to, Contact.all, :phone, :name) %>
  <%= f.label :from %>
  <%= f.text_field :from %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.label :image_url %>
  <%= f.text_field :media_url %>
  <%= f.submit %>
<% end %>

app/views/messages/_message.html.erb
<p><%= link_to message.body, message_path(message) %></p>

app/views/messages/create.js.erb
$('#new_message').remove();
$('#new-message').show();
$('#messages').append('<%= j render(@message) %>');

app/views/messages/index.html.erb
<h2>Messages</h2>
<div id="messages">
<%= render @messages %>
</div>
<p><%= link_to 'New Message', new_message_path, id: "new-message", remote: true %> -or-  <%= link_to 'See Contacts', contacts_path %></p>

app/views/messages/new.html.erb
<h2>New Message</h2>

<% if @message.errors.any? %>
  <p> say what? </p>
  <ul>
    <% @message.error.full_messages.each do |message| %>
        <li> <%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @message do |f| %>
  <%= f.label :to %>
  <%= f.collection_check_boxes(:to, Contact.all, :phone, :name) %>
  <%= f.label :from %>
  <%= f.text_field :from %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.label :image_url %>
  <%= f.text_field :media_url %>
  <%= f.submit %>
<% end %>

app/views/messages/new.js.erb
$('#new-message').hide().after('<%= j render("form") %>');

app/views/messages/show.html.erb
<p>From <%= Contact.find_by(phone: @message.from).name %></p>
<p>To <%= Contact.find_by(phone: @message.to).name %></p>

<p><%= @message.body %></p>
<img src= <%= @message.media_url %>>